name: Trufflehog GitHub Actions
on:
  push:
  pull_request:

jobs:
  trufflehog:
    name: Run trufflehog from current branch (self test)

    permissions:
      actions: read
      contents: read

      pull-requests: write
      security-events: write

    runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Run trufflehog
        uses: trufflesecurity/trufflehog@b06f6d72a3791308bb7ba59c2b8cb7a083bd17e4 # v3.88.26
