name: zizmor GitHub Actions static analysis
on:
  push:
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"
jobs:
  zizmor:
    name: Run zizmor from current branch (self test)

    permissions:
      actions: read
      contents: read

      pull-requests: write
      security-events: write

    uses: grafana/shared-workflows/.github/workflows/reusable-zizmor.yml@b502a15952bab7f72daa1f8ce115491a6d97be59
    with:
      runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
      fail-severity: never
      min-severity: high
      min-confidence: low
