name: Trufflehog Secret Scan

on:
  push:
  pull_request:

jobs:
  trufflehog:
    uses: grafana/shared-workflows/.github/workflows/reusable-trufflehog.yml@pr/trufflehog-scan
    with:
      fail-on-secrets: "true"
      extra_args: ""