name: zizmor GitHub Actions static analysis
on:
  push:
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"
jobs:
  zizmor-check:
    name: Check whether there are things to scan
    permissions:
      contents: read
    runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
    outputs:
      found-files: ${{ steps.zizmor-check.outputs.found-files }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Run zizmor
        id: zizmor-check
        shell: bash
        run: |
          FOUND_FILES=false
          SEARCH=$(find . -path "**/.github/workflows/*.yml" -o -path "**/.github/workflows/*.yaml" -o -path "**/action.yml" -o -path "**/action.yaml")
          if [ -n "$SEARCH" ]; then
              FOUND_FILES=true
          fi
          echo "found-files=${FOUND_FILES}" >> $GITHUB_OUTPUT
  zizmor:
    name: Run zizmor from current branch (self test)

    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write
      security-events: write

    needs:
      - zizmor-check
    if: ${{ needs.zizmor-check.outputs.found-files == 'true' }}

    uses: grafana/shared-workflows/.github/workflows/reusable-zizmor.yml@5793b5cefc1316d82c0d8842e6458a8a3d8cc847
    with:
      runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
      fail-severity: high
      min-severity: high
      min-confidence: low
      extra-args: --offline
