name: zizmor GitHub Actions static analysis
on:
  push:
  pull_request:

jobs:
  zizmor:
    name: Run zizmor from current branch (self test)

    permissions:
      actions: read
      contents: read

      pull-requests: write
      security-events: write

    uses: grafana/shared-workflows/.github/workflows/reusable-zizmor.yml@8fa210559ab2cc62e7b12d3bb9cba19dbc862c11
    with:
      runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
      fail-severity: never
