name: snyk-monitor-ci

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
jobs:
  snyk_scans:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - name: Run Snyk to import ${{ github.event.repository.name }} to Snyk
        continue-on-error: true
        uses: snyk/actions/golang@9adf32b1121593767fc3c057af55b55db032dc04 # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --strict-out-of-sync=false --all-projects --exclude=devenv --tags=repo=${{ github.event.repository.name }}
